### ISSUE TITLE
Can not install  sqlcipher3 and  sqlcipher3-binary on Windows 10

### ISSUE THREAD

**Issue by sylwesterdigital** [coleifer/sqlcipher3#4]
Windows 10
$ uname -a
```
MINGW64_NT-10.0 ASUSPRO 2.8.0(0.309/5/3) 2017-03-21 14:04 x86_64 Msys
```

$ python --version
```
Python 3.8.1
```
$ pip install --verbose sqlcipher3-binary
```
Using pip 20.2.2 from c:\users\flaboy\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)
Non-user install because site-packages writeable
Created temporary directory: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-ephem-wheel-cache-nbz9j5ln
Created temporary directory: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-tracker-wa5nlf62
Initialized build tracking at C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-tracker-wa5nlf62
Created build tracker: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-tracker-wa5nlf62
Entered build tracker: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-req-tracker-wa5nlf62
Created temporary directory: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-k3jdfzu0
1 location(s) to search for versions of sqlcipher3-binary:
* https://pypi.org/simple/sqlcipher3-binary/
Fetching project page and analyzing links: https://pypi.org/simple/sqlcipher3-binary/
Getting page https://pypi.org/simple/sqlcipher3-binary/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/sqlcipher3-binary/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/sqlcipher3-binary/ HTTP/1.1" 304 0
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://files.pythonhosted.org/packages/eb/90/5fdfa3964da4ce7a9b1c2c0f5a1bdcca0e066a14d569e51e0c435a68c06f/sqlcipher3_binary-0.4.0-cp36-cp36m-manylinux1_x86_64.whl#sha256=605ea555a3c7e45ce99376e122ac4cc0e237e43503bbd2bdcd3149c86b3d863d (from https://pypi.org/simple/sqlcipher3-binary/)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://files.pythonhosted.org/packages/e9/00/3902cc32812262c29a43389a269340b2fc3fc85e132fab8c1864e355b7fb/sqlcipher3_binary-0.4.0-cp37-cp37m-manylinux1_x86_64.whl#sha256=73b131e5d62c2776c98bf48e8096407a9febce7386d0b5a772e1a6449e85cc18 (from https://pypi.org/simple/sqlcipher3-binary/)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://files.pythonhosted.org/packages/be/e1/dcb2e23ebd43de1b6a6cde9594343773940eb295f980d47440704a3f9b8a/sqlcipher3_binary-0.4.1-cp36-cp36m-manylinux1_x86_64.whl#sha256=4c7814578ce63ea02647018220ccfae01c56d98e6890b360e71268e9af426fdd (from https://pypi.org/simple/sqlcipher3-binary/)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://files.pythonhosted.org/packages/26/9c/ab66288cd139c5a4f94451d6b5d6cc58d7c55f65bbafd244717f8171694a/sqlcipher3_binary-0.4.1-cp37-cp37m-manylinux1_x86_64.whl#sha256=308935b35fb62d5d1483e98b0fb4df63e5bad0db1818ccd717eabd0f869f0ff3 (from https://pypi.org/simple/sqlcipher3-binary/)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://files.pythonhosted.org/packages/76/17/93eefc6464a281ea760eb5626414c5a6a701ed576a9f8a057fe2e7131b2b/sqlcipher3_binary-0.4.1-cp38-cp38-manylinux1_x86_64.whl#sha256=7d7b6d7e6a82cdea1b795237690fa2c15505a8ab39a44a83dea2312fd5f37873 (from https://pypi.org/simple/sqlcipher3-binary/)
  Skipping link: none of the wheel's tags match: cp36-cp36m-manylinux1_x86_64: https://files.pythonhosted.org/packages/c8/61/27c19addd4b47365702ab499d74ba6a931ee2ebd4489ff38d572f109f6a2/sqlcipher3_binary-0.4.2-cp36-cp36m-manylinux1_x86_64.whl#sha256=52969904c63197a8e4656b50838d7a1cdc374194667c126e5f0a558c4b206b8b (from https://pypi.org/simple/sqlcipher3-binary/)
  Skipping link: none of the wheel's tags match: cp37-cp37m-manylinux1_x86_64: https://files.pythonhosted.org/packages/c2/2a/f5128808a93fd26e5f604f200f22944897c00e93af21927e6770c20c6b96/sqlcipher3_binary-0.4.2-cp37-cp37m-manylinux1_x86_64.whl#sha256=816df8036305cfad27c6ad6c4a4ebfd29fbe7a7364d959588b6dbd29bce69dc0 (from https://pypi.org/simple/sqlcipher3-binary/)
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_x86_64: https://files.pythonhosted.org/packages/b9/a3/0ff5eb964274c3d9de8826e64ce7d6910b57d61c675f604920fd2d2c1fbd/sqlcipher3_binary-0.4.2-cp38-cp38-manylinux1_x86_64.whl#sha256=1f95560820f7495af8a4cd24bc7dab4ec1144b6eae6acd8295a2b569fe81609b (from https://pypi.org/simple/sqlcipher3-binary/)
Given no hashes to check 0 links for project 'sqlcipher3-binary': discarding no candidates
ERROR: Could not find a version that satisfies the requirement sqlcipher3-binary (from versions: none)
ERROR: No matching distribution found for sqlcipher3-binary
Exception information:
Traceback (most recent call last):
  File "c:\users\flaboy\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\base_command.py", line 216, in _main
    status = self.run(options, args)
  File "c:\users\flaboy\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "c:\users\flaboy\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\commands\install.py", line 324, in run
    requirement_set = resolver.resolve(
  File "c:\users\flaboy\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "c:\users\flaboy\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\flaboy\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 339, in _get_abstract_dist_for
    self._populate_link(req)
  File "c:\users\flaboy\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 305, in _populate_link
    req.link = self._find_requirement_link(req)
  File "c:\users\flaboy\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 270, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "c:\users\flaboy\appdata\local\programs\python\python38\lib\site-packages\pip\_internal\index\package_finder.py", line 926, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for sqlcipher3-binary
Removed build tracker: 'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-req-tracker-wa5nlf62'
```

$ pip list
```
Package        Version
-------------- ---------
atomicwrites   1.4.0
attrs          19.3.0
colorama       0.4.3
iniconfig      1.0.1
more-itertools 8.4.0
packaging      20.4
pip            20.2.2
pluggy         0.13.1
py             1.9.0
pyparsing      2.4.7
pytest         6.0.1
setuptools     41.2.0
six            1.15.0
toml           0.10.1
wheel          0.35.0

```

**Comment by coleifer** [comment]
You need libsqlcipher installed for the former, and you have to be running linux for the latter.

**Comment by coleifer** [comment]
https://www.zetetic.net/sqlcipher/open-source/

**Comment by sylwesterdigital** [comment]
Thanks. I've got this sorted on Mac OS and Linux, but tried to mirrro my dev environment on Windows 10 laptop and failed.
